package org.tio.http.server.demo1.model;

import org.tio.http.server.demo1.model.base.BaseBlog;

 /**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Blog extends BaseBlog<Blog> {

	private static final long serialVersionUID = 4286093082174483265L;

}
