package org.tio.http.server.demo1.model;

import org.tio.http.server.demo1.model.base.BaseDonate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Donate extends BaseDonate<Donate> {

	private static final long serialVersionUID = 3998566102930056858L;

}
