package org.tio.http.server.demo1.model;

import org.tio.http.server.demo1.model.base.BaseUserOsc;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserOsc extends BaseUserOsc<UserOsc> {

	private static final long serialVersionUID = 6985776297197499927L;

}
