package org.tio.http.server.demo1.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserOsc<M extends BaseUserOsc<M>> extends Model<M> implements IBean {

	private static final long serialVersionUID = 7995046067570049982L;

	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public java.lang.String getOscid() {
		return get("oscid");
	}

	public java.lang.String getOscnick() {
		return get("oscnick");
