package org.tio.http.server.demo1.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

 /**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
